@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.lawliet.chrono_circuit.datagen.lootTables;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;