@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.lawliet.chrono_circuits.blocks.gratedBlocks.repeater;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;