@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.lawliet.chrono_circuits.blocks.gratedBlocks.torch;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;