@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.lawliet.chrono_circuit.blocks.CopperPressurePlate;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;