@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.lawliet.chrono_circuit.blockEntity.hopper;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;